services:
  app:
    volumes:
      - .:/var/www
    command: sh -c "composer install --ignore-platform-reqs && php-fpm"

  nginx:
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  node:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: npm run dev -- --host
