services:
  # Contenedor principal PHP + Composer + Node
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets-app
    volumes:
      - .:/var/www
    networks:
      - laravel
    command: sh -c "cd /var/www && composer install && chmod -R 775 storage bootstrap/cache && chown -R www-data:www-data storage bootstrap/cache && php-fpm"

  # Node separado para levantar Vite (React)
  node:
    image: node:20
    container_name: tickets-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Vite dev server
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app
    networks:
      - laravel

  # Nginx para servir Laravel
  web:
    image: nginx:alpine
    container_name: tickets-web
    ports:
      - "8000:80" # Laravel backend
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: tickets-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets
      MYSQL_USER: adminserv
      MYSQL_PASSWORD: passserv
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tickets-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: adminserv
      PMA_PASSWORD: passserv
    networks:
      - laravel

volumes:
  db-data:


networks:
  laravel:
    driver: bridge
